// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU8Jey14HNt1vyGBy8E2-zu1X9C10TF9Q',
    appId: '1:114419192277:web:3abd5e3f70939e23c7ed5c',
    messagingSenderId: '114419192277',
    projectId: 'background-task-97f8f',
    authDomain: 'background-task-97f8f.firebaseapp.com',
    storageBucket: 'background-task-97f8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo00jF2d3FpZUzplTZ4y9RDYnbczNjqjo',
    appId: '1:114419192277:android:233cf35474c67937c7ed5c',
    messagingSenderId: '114419192277',
    projectId: 'background-task-97f8f',
    storageBucket: 'background-task-97f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEmeHlDangQKL9EnG4D6QTv2XGJ0Ruc8M',
    appId: '1:114419192277:ios:264a44fc952843cbc7ed5c',
    messagingSenderId: '114419192277',
    projectId: 'background-task-97f8f',
    storageBucket: 'background-task-97f8f.appspot.com',
    iosBundleId: 'com.node.gl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEmeHlDangQKL9EnG4D6QTv2XGJ0Ruc8M',
    appId: '1:114419192277:ios:f13c3820ee596623c7ed5c',
    messagingSenderId: '114419192277',
    projectId: 'background-task-97f8f',
    storageBucket: 'background-task-97f8f.appspot.com',
    iosBundleId: 'com.example.backgroundTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU8Jey14HNt1vyGBy8E2-zu1X9C10TF9Q',
    appId: '1:114419192277:web:ad632d551967a9f5c7ed5c',
    messagingSenderId: '114419192277',
    projectId: 'background-task-97f8f',
    authDomain: 'background-task-97f8f.firebaseapp.com',
    storageBucket: 'background-task-97f8f.appspot.com',
  );
}
